CAMERA_INDEX = 0

FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7

MAX_HANDS = 1

# Cursor settings
FRAME_MARGIN = 100
CURSOR_SMOOTHING = 5
CURSOR_DEAD_ZONE = 3

# Left click settings
PINCH_THRESHOLD = 35
PINCH_RELEASE_THRESHOLD = 50

# Right click settings
RIGHT_CLICK_COOLDOWN = 0.8

# Scrolling settings
SCROLL_THRESHOLD = 12
SCROLL_SPEED = 3

DOUBLE_CLICK_INTERVAL = 0.45


# ==========================================
# HYBRID EYE + HAND CONTROL
# ==========================================

HYBRID_MODE = False

EYE_CURSOR_ENABLED = False

EYE_SENSITIVITY = 1.5

EYE_SMOOTHING = 8

EYE_DEAD_ZONE = 5

# Keyboard controls

HYBRID_TOGGLE_KEY = "f6"
EYE_TOGGLE_KEY = "f7"
HAND_TOGGLE_KEY = "f8"