CAMERA_INDEX = 0

FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7

MAX_HANDS = 1

# Cursor settings
FRAME_MARGIN = 100
CURSOR_SMOOTHING = 5

# Left click settings
PINCH_THRESHOLD = 35
PINCH_RELEASE_THRESHOLD = 50

# Right click settings
RIGHT_CLICK_COOLDOWN = 0.8